const mongoose = require('mongoose');
const passportLocalMongoose = require('passport-local-mongoose');
const Schema = mongoose.Schema;

const userSchema = new Schema({
    // username is auto-generated by passport
    isAdmin: {
        type: Boolean,
        default: false
    },
    library: {
        type: Array,
        default: []
    },
    shelfishUser: {
        type: Boolean,
        default: true
    }
});

// handles adding the username / password fields to the userSchema
// will hash and salt the password
userSchema.plugin(passportLocalMongoose);

// Here, we're exporting a new Mongoose model called User, and saying it uses the userSchema as a framework
module.exports = mongoose.model('User', userSchema);